install:
  - source ./scripts/texlive.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
  - source ./scripts/run.sh check-utf8
  - source ./scripts/run.sh check-gbk-big5

after_failure:
  - cat ./build/test/*.diff
