matrix:
  include:
    - name: "TeX Live"
      install:
        - source ./scripts/texlive.sh
      script:
        - source ./scripts/run.sh check-utf8
        - source ./scripts/run.sh check-gbk-big5
      cache:
        directories:
          - /tmp/texlive
          - $HOME/.texlive
    - name: "MikTeX"
      sudo: required
      services:
        - docker
      install:
        # - docker build -t miktex:ubuntu-18.04 .
        # - docker volume create --name zhlipsum
        - docker pull miktex/miktex
        - docker run --volume miktex:/miktex/.miktex --volume $(pwd):/miktex/work mpm --admin --verbose --repository=https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/ --install adobemapping,amsfonts,amsmath,caption,cjk,cjkpunct,cm,ctablestack,ctex,currfile,dvipdfmx,environ,etex,etoolbox,euenc,fancyhdr,fandol,filehook,fontspec,graphics,graphics-cfg,graphics-def,ifxetex,kantlipsum,knuth-lib,l3build,l3experimental,l3kernel,l3packages,lm,lm-math,ltxbase,lualatex-math,lualibs,luaotfload,luatex85,luatexbase,luatexja,metafont,mfware,miktex-luatex,miktex-tex,miktex-xetex,ms,oberdiek,preview,psnfss,tex-ini-files,tools,trimspaces,ucharcat,ulem,unicode-data,uplatex,varwidth,xcjk2uni,xcolor,xecjk,xkeyval,xunicode,zhmetrics,zhnumber
      before_script:
        - echo $(pwd)
        - chmod --recursive 777 .
      script:
        # - source ./scripts/run.sh check-utf8 --docker miktex:ubuntu-18.04
        # - source ./scripts/run.sh check-gbk-big5 --docker miktex:ubuntu-18.04
        - source ./scripts/run.sh check-utf8 --docker miktex/miktex
        - source ./scripts/run.sh check-gbk-big5 --docker miktex/miktex

after_failure:
  - cat ./build/test/*.diff
