matrix:
  include:
    - name: "TeX Live"
      install:
        - source ./scripts/texlive.sh
      script:
        - source ./scripts/run.sh check-utf8
        - source ./scripts/run.sh check-gbk-big5
      cache:
        directories:
          - /tmp/texlive
          - $HOME/.texlive
    - name: "MikTeX"
      sudo: required
      services:
        - docker
      install:
        # - docker build -t miktex:ubuntu-18.04 .
        - docker pull miktex/miktex
        - docker volume create --name miktex
      before_script:
        - echo $(pwd)
        - chmod -R 777 .
      script:
        #- source ./scripts/run.sh check-utf8 --docker miktex:ubuntu-18.04
        #- source ./scripts/run.sh check-gbk-big5 --docker miktex:ubuntu-18.04
        #- source ./scripts/run.sh check-utf8 --docker miktex/miktex
        #- source ./scripts/run.sh check-gbk-big5 --docker miktex/miktex
        - docker run -v miktex:/miktex/.miktex -v $(pwd):/miktex/work miktex/miktex pdflatex hello.tex
        - docker run -it -v miktex:/miktex/.miktex -v $(pwd):/miktex/work miktex/miktex pdflatex hello.tex

after_failure:
  - cat ./build/test/*.diff
