matrix:
  include:
    - name: "TeX Live"
      install:
        - source ./scripts/texlive.sh
      script:
        - source ./scripts/run.sh check-utf8
        - source ./scripts/run.sh check-gbk-big5
      cache:
        directories:
          - /tmp/texlive
          - $HOME/.texlive
    - name: "MikTeX"
      sudo: required
      services:
        - docker
      before_install:
        - docker build -t miktex:ubuntu-18.04 .
        # - docker pull miktex/miktex
        - docker volume create --name pkg
      install:
      before_script:
        - echo $(pwd)
        - chmod --recursive 777 .
      script:
        # - source ./scripts/run.sh check-utf8 --docker miktex:ubuntu-18.04
        # - source ./scripts/run.sh check-gbk-big5 --docker miktex:ubuntu-18.04
        # - source ./scripts/run.sh check-utf8 --docker miktex/miktex
        # - source ./scripts/run.sh check-gbk-big5 --docker miktex/miktex
        - docker run --volume pkg:/home/miktex/.miktex --volume $(pwd):/home/miktex/work miktex:ubuntu-18.04 echo $(pwd)
        - docker run --volume pkg:/home/miktex/.miktex --volume $(pwd):/home/miktex/work miktex:ubuntu-18.04 ls -al
        - docker run --volume pkg:/home/miktex/.miktex --volume $(pwd):/home/miktex/work miktex:ubuntu-18.04 mpm --list | grep ^i
        - docker run --volume pkg:/home/miktex/.miktex --volume $(pwd):/home/miktex/work miktex:ubuntu-18.04 ls -al /home/miktex/.miktex
        - docker run --volume pkg:/home/miktex/.miktex --volume $(pwd):/home/miktex/work miktex:ubuntu-18.04 ls -al /usr/local/share/miktex-texmf
        # Success
        - docker run --volume pkg:/home/miktex/.miktex --volume $(pwd):/home/miktex/work miktex:ubuntu-18.04 initexmf --version
        - docker run --volume pkg:/home/miktex/.miktex --volume $(pwd):/home/miktex/work miktex:ubuntu-18.04 miktexsetup --version
        - docker run --volume pkg:/home/miktex/.miktex --volume $(pwd):/home/miktex/work miktex:ubuntu-18.04 mpm --version
        # Failure
        - docker run --volume pkg:/home/miktex/.miktex --volume $(pwd):/home/miktex/work miktex:ubuntu-18.04 findtexmf --version
        - docker run --volume pkg:/home/miktex/.miktex --volume $(pwd):/home/miktex/work miktex:ubuntu-18.04 miktex-kpsewhich --version
        - docker run --volume pkg:/home/miktex/.miktex --volume $(pwd):/home/miktex/work miktex:ubuntu-18.04 mthelp --version
        - docker run --volume pkg:/home/miktex/.miktex --volume $(pwd):/home/miktex/work miktex:ubuntu-18.04 pdftex --version
        - docker run --volume pkg:/home/miktex/.miktex --volume $(pwd):/home/miktex/work miktex:ubuntu-18.04 texlua --version

after_failure:
  - cat ./build/test/*.diff
