matrix:
  include:
    - name: "TeX Live"
      install:
        - source ./scripts/texlive.sh
      cache:
        directories:
          - /tmp/texlive
          - $HOME/.texlive
      script:
        - source ./scripts/run.sh check-utf8
        - source ./scripts/run.sh check-gbk-big5
    - name: "MikTeX"
      sudo: required
      install:
        - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
        - echo "deb http://miktex.org/download/ubuntu bionic universe" | sudo tee /etc/apt/sources.list.d/miktex.list
        - sudo apt-get update
        - sudo apt-get install miktex
        - miktexsetup finish
      script:
        - miktex-tex --version
        - miktex-pdftex --version
        - miktex-xetex --version
        - miktex-luatex --version

after_failure:
  - cat ./build/test/*.diff
