matrix:
  include:
    - name: "TeX Live"
      install:
        - source ./scripts/texlive.sh
      script:
        - source ./scripts/run.sh check-utf8
        - source ./scripts/run.sh check-gbk-big5
      cache:
        directories:
          - /tmp/texlive
          - $HOME/.texlive
    - name: "MikTeX"
      sudo: required
      services:
        - docker
      install:
        - docker pull nanmu42/tex-package-test-bench
        - docker volume create --name packages
      before_script:
        - source ./travis-ci/miktex/before-script.sh
      script:
        - source ./scripts/run.sh check-utf8     --docker
        - source ./scripts/run.sh check-gbk-big5 --docker
after_failure:
  - cat ./build/test/*.diff
