install:
  - source ./scripts/texlive.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
  - mkdir test
  - cd source
  - xetex zhlipsum.dtx
  - source ../scripts/zhconvert.sh
  - cp *.sty  ../test
  - cp *.def  ../test
  - cp *.tex  ../test
  - cd ../test
  - latex    -interaction=nonstopmode zhlipsum-example-gbk
  - latex    -interaction=nonstopmode zhlipsum-example-utf8
  # - pdflatex -interaction=nonstopmode zhlipsum-example-gbk
  # - pdflatex -interaction=nonstopmode zhlipsum-example-utf8
  - xelatex  -interaction=nonstopmode zhlipsum-example-utf8
  - lualatex -interaction=nonstopmode zhlipsum-example-utf8
  - uplatex  -interaction=nonstopmode zhlipsum-example-utf8
